[tool.poetry]
name = "chatgpt-share-backend"
version = "0.3.5"
description = ""
authors = ["moeakwak <moeakwak@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.0"
uvicorn = "^0.21.1"
aiosqlite = "^0.18.0"
sqlalchemy = "^2.0.7"
fastapi-users-db-sqlalchemy = "^5.0.0"
revchatgpt = "4.1.1"
greenlet = "^2.0.2"
websockets = "^10.4"
setuptools = "^67.6.0"
python-dateutil = "^2.8.2"
pyyaml = "^6.0"
alembic = "^1.10.2"
colorlog = "^6.7.0"
asgiref = "^3.6.0"
aiocron = "^1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
